### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by d4ncer** [d4ncer/.emacs.d#25]
https://github.com/ananthakumaran/tide

**Comment by chrisbarrett** [comment]
I set up TS this evening. Nothing too hard.  :)

https://github.com/chrisbarrett/.emacs.d/blob/4a60bb071a5ac9a86828297f7a265bfc16d5136b/config/cb-web-mode.el#L388

You'll wanna look at my last day of commits for the changes I made to some other packages as part of this.

**Comment by d4ncer** [comment]
Awesome, thanks @chrisbarrett!

**Comment by d4ncer** [comment]
don't need this atm, and want to set it up ideally with LSP. will re-open then.
