### ISSUE TITLE
Build dark theme

### ISSUE THREAD

**Issue by d4ncer** [d4ncer/.emacs.d#45]
For balance

**Comment by galczo5** [comment]
Check out https://github.com/hlissner/emacs-doom-themes/tree/screenshots

**Comment by d4ncer** [comment]
While I do have `doom-themes` installed for presentations and the like, I prefer monotonic themes that rely on font-weight & grayscale to create visual rhythm rather than colour. Something more on the lines of https://emacsthemes.com/themes/tao-theme.html

**Comment by galczo5** [comment]
Ok, I understand. You're looking for something like https://github.com/voloyev/sexy-monochrome-theme

It need only few customizations like mode-line background color and it's quite fine. I have tried it with gray mode-line.

Here is customization code:

```
(defun customize-theme ()
  "my theme customs"
  ;; (set-background-color "#101010")
  (set-face-background 'mode-line "#0a0a0a")
  (set-face-attribute 'mode-line nil
                      :box '(:line-width 4 :color "#0a0a0a"))
  (set-face-background 'mode-line-inactive "#0a0a0a")
  (set-face-attribute 'mode-line-inactive nil
                      :box '(:line-width 4 :color "#0a0a0a"))
  (set-face-background 'linum "#212121")
  (set-face-attribute 'mode-line nil :height 100 :weight 'light)
  (set-face-background 'vertical-border "#1A1A1A")
  (set-face-foreground 'vertical-border (face-background 'vertical-border))
  ;; (set-cursor-color "#ffffff")
  )
```
