### ISSUE TITLE
find file dialog obscures last row option when path is longer than 2 rows

### ISSUE THREAD

**Issue by jackyzhen** [d4ncer/.emacs.d#55]
Working normally:
![image](https://user-images.githubusercontent.com/8305630/62101684-5df5ec00-b2ea-11e9-8114-913e2c393638.png)

Last row obsured:
![image](https://user-images.githubusercontent.com/8305630/62101625-2b4bf380-b2ea-11e9-821b-b28628517025.png)

**Comment by d4ncer** [comment]
Oooh, this is fun. Will take a look this weekend.

**Comment by d4ncer** [comment]
Closing this as I've stopped using childframes for `ivy`/`swiper`.
